(() => {
 const root=document.getElementById('pulse-lab'), q=id=>root.querySelector('#pl-'+id);
 const canvas=q('canvas'), ctx=canvas.getContext('2d'), status=q('status');
 const oscillators=new Set();
 let ac,analyser,output,source,stream,buffer=null,timer=null,active=false,kind='demo',token=0,trackName='' ;
 let freq=new Uint8Array(512),wave=new Uint8Array(1024),w=600,h=320,color='',neutral='';
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function colors(){const el=document.createElement('span');root.append(el);el.style.color='var(--viz-series-1)';color=getComputedStyle(el).color;el.style.color='var(--border)';neutral=getComputedStyle(el).color;el.remove()}
 function resize(){w=canvas.clientWidth;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);colors();draw(0)}
 new ResizeObserver(resize).observe(canvas);
 new MutationObserver(colors).observe(document.documentElement,{attributes:true,attributeFilter:['class','style']});
 function save(){try{localStorage.setItem('pulse-lab-settings',JSON.stringify({modelContent:{style:q('style').value,sensitivity:Number(q('gain').value)},privateContent:{volume:Number(q('volume').value)}}))}catch{}}
 function restore(s){if(!s)return;const m=s.modelContent||{},p=s.privateContent||{};if(['orbit','bars','wave'].includes(m.style))q('style').value=m.style;if(m.sensitivity>=.5&&m.sensitivity<=3)q('gain').value=m.sensitivity;if(p.volume>=0&&p.volume<=1)q('volume').value=p.volume;labels()}
 function labels(){q('gain-label').textContent=Number(q('gain').value).toFixed(1)+'×';q('volume-label').textContent=Math.round(q('volume').value*100)+'%';if(output)output.gain.value=Number(q('volume').value)}
 try{restore(JSON.parse(localStorage.getItem('pulse-lab-settings')))}catch{}
 for(const id of ['style','gain','volume'])q(id).addEventListener('input',()=>{labels();save();if(!active)draw(0)});
 async function init(){if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();analyser=ac.createAnalyser();analyser.fftSize=1024;analyser.smoothingTimeConstant=.82;output=ac.createGain();output.gain.value=Number(q('volume').value);analyser.connect(output);output.connect(ac.destination)}await ac.resume()}
 function stop(){token++;active=false;for(const osc of oscillators){try{osc.stop()}catch{}osc.disconnect()}oscillators.clear();clearInterval(timer);timer=null;if(source){try{source.stop()}catch{}source.disconnect();source=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(ac)ac.suspend();status.textContent='Stopped';q('play').textContent=buffer?'Play track':'Play demo';draw(0)}
 function beat(){const now=ac.currentTime;for(let i=0;i<4;i++){const t=now+i*.25;const osc=ac.createOscillator(),g=ac.createGain();osc.type=i%2?'triangle':'sine';osc.frequency.setValueAtTime(i%2?220:110,t);osc.frequency.exponentialRampToValueAtTime(i%2?110:40,t+.18);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(i%2?.12:.5,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+.23);osc.connect(g);g.connect(analyser);oscillators.add(osc);osc.start(t);osc.stop(t+.24);osc.onended=()=>{oscillators.delete(osc);osc.disconnect();g.disconnect()}}}
 async function play(){stop();const turn=token;q('error').textContent='';try{await init();if(turn!==token)return;analyser.disconnect();analyser.connect(output);kind=buffer?'track':'demo';active=true;if(buffer){source=ac.createBufferSource();source.buffer=buffer;source.connect(analyser);source.onended=()=>{if(turn===token)stop()};source.start()}else{beat();timer=setInterval(beat,1000)}status.textContent=buffer?'Playing · '+trackName:'Playing · synthetic beat';q('play').textContent='Restart';}catch(e){q('error').textContent='Audio could not start in this browser. '+e.message;active=false}}
 q('play').onclick=play;q('stop').onclick=stop;
 q('file').onchange=async()=>{const file=q('file').files[0];if(!file)return;stop();const turn=token;buffer=null;q('play').disabled=true;status.textContent='Loading audio…';try{await init();const decoded=await ac.decodeAudioData(await file.arrayBuffer());if(turn!==token)return;buffer=decoded;trackName=file.name;q('play').textContent='Play track';status.textContent='Ready · '+file.name;q('error').textContent=''}catch(e){if(turn!==token)return;status.textContent='Ready · synthetic demo';q('play').textContent='Play demo';q('error').textContent='This audio file could not be decoded. Try an MP3 or WAV.'}finally{q('play').disabled=false;if(turn===token&&!active&&ac)ac.suspend()}};
 q('mic').onclick=async()=>{stop();const turn=token;q('error').textContent='';try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Microphone access is unavailable in this browser. Use HTTPS or localhost for microphone access, or choose an audio file or the demo.');await init();if(turn!==token)return;const incoming=await navigator.mediaDevices.getUserMedia({audio:true});if(turn!==token){incoming.getTracks().forEach(t=>t.stop());return}stream=incoming;analyser.disconnect();source=ac.createMediaStreamSource(stream);source.connect(analyser);kind='mic';active=true;status.textContent='Listening · microphone'}catch(e){if(turn!==token)return;q('error').textContent=e.name==='NotAllowedError'?'Microphone access was denied or is blocked by this browser. Use HTTPS or localhost for microphone access, or choose an audio file or the demo.':e.message;if(ac)ac.suspend()}};
 function draw(t){ctx.clearRect(0,0,w,h);const gain=Number(q('gain').value),mode=q('style').value;ctx.strokeStyle=neutral;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(active){analyser.getByteFrequencyData(freq);analyser.getByteTimeDomainData(wave)}else{freq.fill(0);wave.fill(128)}ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;
 if(mode==='wave'){ctx.beginPath();for(let i=0;i<wave.length;i++){const x=i/(wave.length-1)*w,y=h/2+Math.max(-1,Math.min(1,(wave[i]-128)/128*gain))*h*.4;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}
 else if(mode==='bars'){const n=64,bw=w/n;for(let i=0;i<n;i++){const k=Math.floor(Math.pow(i/(n-1),2)*400),v=Math.min(1,freq[k]/255*gain),bh=2+v*250;ctx.globalAlpha=.35+.65*v;ctx.fillRect(i*bw+1,(h-bh)/2,Math.max(1,bw-3),bh)}ctx.globalAlpha=1}
 else {const n=120,r=Math.min(w*.23,85),cx=w/2,cy=h/2;for(let i=0;i<n;i++){const a=i/n*Math.PI*2-Math.PI/2,k=Math.floor(Math.pow((i%n)/n,2)*330),v=Math.min(1,freq[k]/255*gain),len=4+v*55;ctx.globalAlpha=.3+.7*v;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.lineTo(cx+Math.cos(a)*(r+len),cy+Math.sin(a)*(r+len));ctx.stroke()}ctx.globalAlpha=1;ctx.beginPath();ctx.arc(cx,cy,r*.75,0,Math.PI*2);ctx.stroke()}}
 let last=0;function frame(t){if(t-last>(reduced?140:25)){draw(t);last=t}requestAnimationFrame(frame)}resize();requestAnimationFrame(frame);
 window.addEventListener('pagehide',stop);
})();
